#!/bin/sh

echo "test" | awk 'BEGIN{ system("echo directory:"); system("du -h -d 1 | sort -k 1hr -k 2n | sed 1d") } { system("echo file:"); system("find . -maxdepth 1 -type f -exec du -ah {} + | sort -k 1hr -k 2n") } END{ system("echo total:") system("du -h -d 0") } ' | awk '{if (substr($1, 1, 1) == "d" || substr($1, 1, 1) == "f" || substr($1, 1, 1) == "t") print $0; else if ($2 == ".") print "\t" $1 "\t" "total"; else print "\t" $1 "\t" substr($2, 3); }'
