#!/bin/sh

printf "1\n2\n3" | awk '{ typ = $0; if (typ == "1") print "directory:"; else if (typ == "2") print "file:"; else if (typ == "3") print "total:"; tmp = "find . -maxdepth 1 -exec du -h -d 0 {} + | sort -k 1hr -k 2n -k 1" typ "n"; while ((tmp | getline) > 0) { if (typ == "1") { if (system("test -d " $2) == 0) { if ( $2 != ".") print "\t" $1 "\t" substr($2, 3); } } if (typ == "2") { if (system("test -f " $2) == 0) print "\t" $1 "\t" substr($2, 3); } if (typ == "3") { if ($2 == ".") print "\t" $1 "\ttotal"; } } }'
